### ISSUE TITLE
execute commands from stdin

### ISSUE THREAD

**Issue by baztian** [tribut/kpcli#1]
Would be nice to be able to supply commands to execute inside the cli from subprocess.
Something like

    kpcli ls

I even tried this one without success

    (echo mypasswd && echo help) | kpcli --kdb ~/mypass.kdbx
    Please provide the master password: *************************
    KeePass CLI (kpcli) v2.7 is ready for operation.
    Type 'help' for a description of available commands.
    Type 'help <command>' for details on individual commands.
    
    kpcli:/> 

Help is not being executed.

**Comment by tribut** [comment]
Have you tried `kpcli --command ls`?

Also note that this is just my private mirror, not affiliated with the project in any way. If you want to request a feature, please try https://sourceforge.net/p/kpcli/feature-requests/

**Comment by baztian** [comment]
Thanks!

**Comment by baztian** [comment]
https://sourceforge.net/p/kpcli/feature-requests/15/

**Comment by tribut** [comment]
Maybe you misunderstood. `--command` is a thing that actually works. I just wasn't sure if you wanted more than what `--command` can do.

**Comment by baztian** [comment]
Thanks. I'm using the ubuntu version that ships kpcli 2.7.
Cloned your repo and it works.
